// ===== JanSathi AI — Government Schemes Knowledge Base =====
// Subset of real central government schemes for MVP

export const SCHEMES_DATA = [
    {
        id: "pm-awas-yojana",
        name: "PM Awas Yojana (Gramin)",
        nameHi: "प्रधानमंत्री आवास योजना (ग्रामीण)",
        category: "Housing",
        description: "Financial assistance for construction of pucca house for rural homeless.",
        descriptionHi: "ग्रामीण बेघरों को पक्का मकान बनाने के लिए वित्तीय सहायता।",
        eligibility: {
            incomeMax: 300000,
            categories: ["BPL", "SC", "ST", "OBC", "Minority"],
            hasNoPuccaHouse: true,
            rural: true,
        },
        benefits: "₹1.20 lakh (plain areas) / ₹1.30 lakh (hilly areas)",
        documents: ["Aadhaar Card", "Income Certificate", "BPL Card", "Land Documents", "Bank Passbook"],
        applicationProcess: [
            "Visit nearest Gram Panchayat office",
            "Fill application form with documents",
            "Verification by Block Development Officer",
            "Approval and first installment release",
        ],
        website: "https://pmayg.nic.in",
    },
    {
        id: "pm-kisan",
        name: "PM Kisan Samman Nidhi",
        nameHi: "पीएम किसान सम्मान निधि",
        category: "Agriculture",
        description: "₹6,000 per year direct income support to farmer families.",
        descriptionHi: "किसान परिवारों को ₹6,000 प्रति वर्ष सीधी आय सहायता।",
        eligibility: {
            isLandOwner: true,
            landMax: 5, // hectares
            categories: ["All farmers with cultivable land"],
        },
        benefits: "₹6,000/year in 3 installments of ₹2,000",
        documents: ["Aadhaar Card", "Land Records (Khasra/Khatauni)", "Bank Account Details", "Mobile Number"],
        applicationProcess: [
            "Visit pmkisan.gov.in or nearest CSC center",
            "Register with Aadhaar and land details",
            "State government verifies land ownership",
            "Amount credited to bank account in 3 installments",
        ],
        website: "https://pmkisan.gov.in",
    },
    {
        id: "ayushman-bharat",
        name: "Ayushman Bharat (PM-JAY)",
        nameHi: "आयुष्मान भारत (पीएम-जय)",
        category: "Health",
        description: "Free health insurance of ₹5 lakh per family per year for secondary and tertiary care.",
        descriptionHi: "माध्यमिक और तृतीयक देखभाल के लिए प्रति परिवार ₹5 लाख प्रति वर्ष का मुफ्त स्वास्थ्य बीमा।",
        eligibility: {
            incomeMax: 200000,
            categories: ["BPL", "SECC listed families"],
            rural: true,
        },
        benefits: "₹5 lakh free health coverage per family per year",
        documents: ["Aadhaar Card", "Ration Card", "SECC Inclusion Letter", "Family ID"],
        applicationProcess: [
            "Check eligibility at mera.pmjay.gov.in",
            "Visit nearest Ayushman Mitra at empanelled hospital",
            "Get Ayushman Bharat Golden Card",
            "Show card at any empanelled hospital for free treatment",
        ],
        website: "https://pmjay.gov.in",
    },
    {
        id: "ujjwala-yojana",
        name: "PM Ujjwala Yojana",
        nameHi: "प्रधानमंत्री उज्ज्वला योजना",
        category: "LPG/Energy",
        description: "Free LPG connection to women from BPL households.",
        descriptionHi: "बीपीएल परिवारों की महिलाओं को मुफ्त एलपीजी कनेक्शन।",
        eligibility: {
            categories: ["BPL", "SC", "ST", "PMAY beneficiary", "Antyodaya"],
            gender: "Female head of household",
        },
        benefits: "Free LPG connection + first refill + stove",
        documents: ["Aadhaar Card", "BPL Card/Ration Card", "Bank Account", "Passport Photo"],
        applicationProcess: [
            "Visit nearest LPG distributor (HP/Bharat/Indane)",
            "Fill KYC form with BPL/Ration card",
            "Submit documents and photo",
            "LPG connection issued within 7-15 days",
        ],
        website: "https://www.pmujjwalayojana.com",
    },
    {
        id: "ladli-behna",
        name: "Ladli Behna Yojana",
        nameHi: "लाडली बहना योजना",
        category: "Women Welfare",
        description: "₹1,250 per month to women (MP, similar schemes in other states).",
        descriptionHi: "महिलाओं को ₹1,250 प्रति माह (मध्य प्रदेश, अन्य राज्यों में समान योजनाएं)।",
        eligibility: {
            ageMin: 21,
            ageMax: 60,
            incomeMax: 250000,
            maritalStatus: ["Married", "Widow", "Divorced"],
            state: "Madhya Pradesh",
        },
        benefits: "₹1,250/month direct bank transfer",
        documents: ["Aadhaar Card", "Samagra ID", "Bank Account", "Passport Photo"],
        applicationProcess: [
            "Apply online at cmladlibahna.mp.gov.in",
            "Or visit nearest gram panchayat/camp",
            "Submit Aadhaar and Samagra ID",
            "Amount credited monthly to bank account",
        ],
        website: "https://cmladlibahna.mp.gov.in",
    },
    {
        id: "sukanya-samriddhi",
        name: "Sukanya Samriddhi Yojana",
        nameHi: "सुकन्या समृद्धि योजना",
        category: "Savings/Girl Child",
        description: "High-interest savings scheme for girl child education and marriage.",
        descriptionHi: "बालिका की शिक्षा और विवाह के लिए उच्च ब्याज बचत योजना।",
        eligibility: {
            childAgeMax: 10,
            childGender: "Female",
            maxChildrenPerFamily: 2,
        },
        benefits: "8.2% interest rate (highest among small savings), tax-free",
        documents: ["Girl's Birth Certificate", "Parent's Aadhaar", "Address Proof", "Photo"],
        applicationProcess: [
            "Visit nearest Post Office or Bank",
            "Open account with minimum ₹250",
            "Deposit up to ₹1.5 lakh per year",
            "Account matures when girl turns 21",
        ],
        website: "https://www.india.gov.in/sukanya-samriddhi-yojna",
    },
];

export type SchemeData = (typeof SCHEMES_DATA)[number];
